### ISSUE TITLE
f37 woes

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/sodalite#56]
[Thanks to Terra](https://github.com/sodaliterocks/sodalite/issues/44#issuecomment-1370384483), we now have a working build of Sodalite 37 (currently available in `sodalite/f37/<arch>/<variant>` branches), but its not without its problems:

- [ ] **Calendar** (Flatpak) does not open, and errors out with: &mdash; #57<br/><code>(io.elementary.calendar:2): GLib-CRITICAL **: 19:01:42.255: g_strsplit: assertion 'string != NULL' failed</code>
- [x] **Videos** (Flatpak) does not open, and errors out with: &mdash; #57<br/>```(io.elementary.videos:2): GLib-CRITICAL **: 19:04:35.760: g_strsplit: assertion 'string != NULL' failed```
- [x] ~~Indicators are broken~~ &mdash; We won't bother; it's just more work for us maintain something that's essentially obsolete
  - ~~Is this really worth fixing though? Indicators in Linux are unmaintained and nigh dead, and some apps will stay on the dock when they're running in the background (TDesktop does this, for example)~~
  - ~~elementaryOS itself also doesn't have indicators, and users have to rely on the same hacks we've employed into Sodalite so far~~
- [x] **User Accounts** Switchboard plug is missing &mdash; https://github.com/sodaliterocks/sodalite/commit/cd1c9fbd4b18b18adfbcb3e44ef0ef7b66733a53
  - `libgnome-desktop-3` dependency is missing from Terra
  - Slightly difficult to live without this as it causes a UX bug: **Power ➔ User Accounts Settings...** ends up on the main Switchboard panel
- [x] `next` version (`sodalite/next/<arch>/<variant>`) does not build &mdash; #51

Once these major tasks are rectified, we can consider shipping 37 on the `stable` version branches.

**Comment by AloneER0** [comment]
I don't think indicators are really that needed because well there are a few reasons:

- It's a hack
Which can stop working completely at any time soon.

- As you've said before ElementaryOS already removed them completely from the latest version of Pantheon so why fight with Pantheon by adding hacks.

- Videos and Calendar probably won't happen because of the missing dependency in Terra repo.


I really hope this isn't the end of Sodalite since, I really want to continue to use it full time because it allows me to mix rpm-ostree with Pantheon.

There has to be a way to fix it. 🤔

**Comment by electricduck** [comment]
>   - Videos and Calendar probably won't launch because of the missing dependency in Terra repo.

These are coming from Flatpak though; missing dependencies in the image shouldn't really be affecting them. I **think** what we're missing is a runtime that exists on Flathub (since elementaryOS has one pre-installed to make Epiphany work). Need to spin up elementaryOS 7.0 at some point to have a look.

> I don't think indicators are really that needed because well there are a few reasons:
> 
>   - It's a hack
>     Which can stop working completely at any time soon.
> 
>   - As you've said before ElementaryOS already removed them completely from the latest version of Pantheon so why fight with Pantheon by adding hacks.

I agree entirely, tbf. As much as it irritates me personally not having them with various apps, the fault really lies on the developers still insisting on using them even after its been warned time and time again they are obsoleted.

**Comment by AloneER0** [comment]
Maybe it's the gnome platform?

**Comment by electricduck** [comment]
> From where did you get those apps flathub or?

The elementary apps come from elementary's own Flatpak repository (which powers AppCenter)

**Comment by AloneER0** [comment]
Maybe they're missing the elementary runtime

**Comment by electricduck** [comment]
These are the apps currently installed on elementaryOS 6.1

```
elementary@elementary:~$ flatpak remotes
Name        Options
appcenter   system
freedesktop system,filtered
appcenter   user
elementary@elementary:~$ flatpak list
Name            Application ID             Version Branch Origin      Installation
elementary pla… io.elementary.Platform             6      appcenter   system
elementary pla… io.elementary.Platform             6.1    appcenter   system
Calculator      io.elementary.calculator   1.7.2   stable appcenter   system
Camera          io.elementary.camera       6.0.3   stable appcenter   system
Captive Networ… ….elementary.capnet-assist 2.4.0   stable appcenter   system
Screenshot      io.elementary.screenshot   6.0.2   stable appcenter   system
Videos          io.elementary.videos       2.8.1   stable appcenter   system
Mesa            …sktop.Platform.GL.default 21.3.1  21.08  freedesktop system
GNOME Web       org.gnome.Epiphany         41.0    stable appcenter   system
Evince          org.gnome.Evince           41.3    stable appcenter   system
File Roller     org.gnome.FileRoller       3.38.0  stable appcenter   system
```

Two things to note:
 - `org.freedesktop.Platform.GL.default` from `freedesktop` is there for Epiphany (`org.gnome.Epiphany`) to work
 - Videos, amusingly, doesn't seem to launch on elementaryOS either currently, so there's actually a problem in the upstream it seems

**Comment by AloneER0** [comment]
Do you have `io.elementary.Platform` installed?

It's needed for Pantheon apps

**Comment by electricduck** [comment]
> Do you have `io.elementary.Platform` installed?
> 
> It's needed for Pantheon apps

Of course, this is a dependency on Pantheon's Flatpak applications

>     * **Videos**, amusingly, **doesn't seem to launch on elementaryOS out-of-the-box**. Apparently its also missing something required to get it working (on the Live CD, at least) — [Video app is not working on 6.1 elementary/videos#295](https://github.com/elementary/videos/issues/295)

Having actually done what was suggested in the ticket, its still broken on elementaryOS 6.1 too. So, indeed, we're suffering an upstream problem that's out of ours hands.

**Comment by AloneER0** [comment]
The videos app not launching ootb on ElementaryOS 6.1 was fixed in https://github.com/elementary/videos/pull/293

**Comment by AloneER0** [comment]
Calendar does launch?

**Comment by electricduck** [comment]
> The videos app not launching ootb on ElementaryOS 6.1 was fixed in [elementary/videos#293](https://github.com/elementary/videos/pull/293)

It's still broken on both Sodalite and elementaryOS 6.1 as far as I can tell, both with Videos 2.9.0 and `org.freedesktop.Platform.ffmpeg-full` 22.08.

> Calendar does launch?

Calendar isn't coming from Flatpak on elementaryOS yet, but after installing it, its also suffering the same problem.

**Comment by AloneER0** [comment]
So we can't do anything about it then.

**Comment by AloneER0** [comment]
Is actually Installing Pantheon Calendar as a flatpak needed on Sodalite?

**Comment by electricduck** [comment]
> Is actually Installing Pantheon Calendar as a flatpak needed on Sodalite?

There's two reasons we started migrating to Flatpak apps on Sodalite:
 - elementaryOS is doing it this way
 - Because of the whole situation pre-Terra, since apps were virtually going unmaintained, so using the Flatpak versions let us adopt the newer versions easier

What we can do now, however, is drop Calendar and Videos to the versions from the repos (in f37's case, from Terra) so they actually work. At a later date we can migrate back to Flatpak versions of the apps when the seem to actually work.

**Comment by AloneER0** [comment]
I actually wonder what broke those apps tho

**Comment by AloneER0** [comment]
I can actually try to see what broke although I will need a sodalite system.

I don't want Pantheon apps running on Plasma.

Is rebuilding to Sodalite safe for test purpose?

**Comment by electricduck** [comment]
> I can actually try to see what broke although I will need a sodalite system.
> 
> I don't want Pantheon apps running on Plasma.
> 
> Is rebuilding to Sodalite safe for test purpose?

I have not tried rebasing from Kinonite, but I see no reason why it would cause problems. Going back you'll just need to manually uninstall various Pantheon apps that were installed from Flatpak (which is pretty easy). If you're really worried about using your own machine though I'd recommend just slapping it on a VM -- it'll also rule out any environmental issues.

**Comment by AloneER0** [comment]
I mean my laptop is a testing environment so it's fine.

And if the rebase will fail, I can always boot into the previous image! (Thanks Silverblue)

So, I will rebase today and then try to figure out why Pantheon Calendar is crashing with that very _informative_ error.

**Comment by AloneER0** [comment]
Well about the libgnome-desktop3 hack maybe it will work for long enough until something better will come out?

**Comment by electricduck** [comment]
> Well about the libgnome-desktop3 hack maybe it will work for long enough until something better will come out?

It seems to, and if a repo suddenly provides this file the build server will just stop building and we can rectify it. As far as I can tell, this also will not affect anything else apart from extreme edge-cases.

**Comment by electricduck** [comment]
> > I don't think indicators are really that needed because well there are a few reasons:
> > 
> > * It's a hack
> >   Which can stop working completely at any time soon.
> > * As you've said before ElementaryOS already removed them completely from the latest version of Pantheon so why fight with Pantheon by adding hacks.
> 
> I agree entirely, tbf. As much as it irritates me personally not having them with various apps, the fault really lies on the developers still insisting on using them even after its been warned time and time again they are obsoleted.

@asjur @1280px

Don't mean to call anyone out, but I noticed some negative reactions to the removal of Indicators &mdash; I've tried to reinstate them but there's practically nothing I can do at this point, and I don't have the time or really the know-how to write something myself. The only reason they continue to work in eOS 7.0 is because its sitting on an old version of Ubuntu which provides various old versions of packages, which would require an insane amount of work to get working on the much more modern Fedora 37. Its worth pointing out these Indicators will also eventually stop working in Ubuntu and eOS.

Complain to app developers: they've been warned for over 3 years that this is the end of them and to use background persisting instead.

**Comment by asjur** [comment]
> Complain to app developers: they've been warned for over 3 years that this is the end of them and to use background persisting instead.

Some things belong as an indicator. See applications such as synchting, spideroak, resilio sync, dropbox, mega etc etc.
Background persistence doesn't replace all functionality.

Anyway, I am not here to maintain a project I am not using. I simply voiced my opinion on ditching indicators on a project I would like to use in the future.

**Comment by 1280px** [comment]
> Don't mean to call anyone out, but I noticed some negative reactions to the removal of Indicators — I've tried to reinstate them but there's practically nothing I can do at this point, and I don't have the time or really the know-how to write something myself. The only reason they continue to work in eOS 7.0 is because its sitting on an old version of Ubuntu which provides various old versions of packages, which would require an insane amount of work to get working on the much more modern Fedora 37. Its worth pointing out these Indicators will also eventually stop working in Ubuntu and eOS.

That's fine, and thanks for the explanation. By disliking I only meant it's bad to see it gone, as, well, removing compatibility layers is never to the good.

> You are however quite welcome to submit a PR if you're willing to come up with a solution.

I would if I could, though for me most of the scripts in this repo look like a black magic mixed with some shell files :D

**Comment by electricduck** [comment]
> That's fine, and thanks for the explanation. By disliking I only meant it's bad to see it gone, as, well, removing compatibility layers is never to the good.

Oh, don't get me wrong, I entirely agree with that. There's two apps I use that rely on indicators (Discord and Nextcloud Desktop) so I myself am even going to find it a niggle.

> I would if I could, though for me most of the scripts in this repo look like a black magic mixed with some shell files :D

If you ever need help, don't hesitate to ask. I realize Sodalite's repo is rather overwhelming compared to other rpm-ostree-based distros.
